# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJ3rhU5BIIfaj9N1Kyslwa73xHaZ9Mpc
"""

!pip install streamlit

import streamlit as st
import joblib
import numpy as np

# Load the trained model
model = joblib.load("titanic_model.pkl")

# Streamlit UI
st.title("Titanic Survival Prediction")

# Input fields in the sidebar
st.sidebar.header("Passenger Details")
pclass = st.sidebar.selectbox("Passenger Class (1 = First, 2 = Second, 3 = Third)", [1, 2, 3])
sex = st.sidebar.selectbox("Gender", ["Male", "Female"])
age = st.sidebar.slider("Age", 0, 100, 25)

# Preprocess user inputs
sex_encoded = 1 if sex == "Male" else 0
features = np.array([[pclass, sex_encoded, age]])

# Predict and display
if st.sidebar.button("Predict"):
    prediction = model.predict(features)
    survival = "Survived" if prediction[0] == 1 else "Did not survive"
    st.write(f"### Prediction: {survival}")

